project:
  type: website

website:
  title: "traveling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/suj93s
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css



